version: '3.8'  

services:
  app:
    image: vickeydockercontainer/igotskill-task:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3600:3600" 
    environment:
      - NODE_ENV=production
      - DB_HOST=mongodb  
      - DB_PORT=27017
      - DB_NAME=gotSkills
      - JWT_SECRET=vickeyshrivastavaiamnodejsdeveloper
    depends_on:
      - mongodb 
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  
    environment:
      - MONGO_INITDB_DATABASE=gotSkills
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
